/*
 * GENERATED by tools/scripts/emit_eqlib_headers.py
 *
 * Struct:        CharacterZoneClient
 * sizeof:        0x9b8
 * Field count:   102
 * Source:        czc_state_table.py
 *
 * This is a canonical reference dump of our Python registry for
 * CharacterZoneClient. It is NOT the integration target -- the upstream
 * Krakty/eqlib:apr15-2026-live header carries inheritance chains,
 * method declarations, and aggregate type usages that this file does
 * not attempt to reproduce.
 *
 * Format matches upstream's `/*0xNNNN*/ type name;` convention so a
 * manual reviewer can diff the field list side-by-side. Confidence
 * and evidence columns are carried as end-of-line comments.
 */

#pragma once

#include <cstdint>

namespace eqlib {

class [[offsetcomments]] CharacterZoneClient
{
public:

/*0x0000*/ uint64_t                     vftable;  // [HIGH] CZC vftable. Ctor @ 0x1400E9EDA LEA RAX,[0x14088F6E8]; MOV [RCX],RAX. Indirect read: Max_Mana @ 0x1402F732F via *(......
/*0x0004*/ uint32_t                     vbtable_displacement;  // [HIGH] vbtable displacement (delta to CharacterBase sub-object). Ctor writes MOV [RDX+RCX+0x4], R8D where R8D = [RAX+0x4] + ...
/*0x0008*/ uint64_t                     vbtable;  // [HIGH] vbtable ptr (CZC -> CharacterBase). Ctor @ 0x1400E9EEB MOV RAX,[RCX+0x8]; MOVSXD RDX,[RAX+0x4]; LEA RAX,[0x14088F7A0]...
/*0x0010*/ void*                        me;  // [HIGH] me (PlayerClient*). InitBonusCache @ 0x140103D10 MOV [RCX+0x10], R9 (=0). Ctor @ 0x1400EA079 MOV [RBX+0x10], RDI (=0)...
/*0x0018*/ uint8_t                      statDirtyFlag;  // [HIGH] bool statDirty. InitBonusCache @ 0x140103D07 MOV word [RCX+0x18], 0x1 -- low byte=1 (dirty=true). Explicit 2-byte wri...
/*0x0019*/ uint8_t                      zoningStatProcessing;  // [HIGH] bool zoningStatProcessing. High byte of the 0x140103D07 word-write (=0). Reader: Cur_HP *(char*)(param_1 + 0x19) cont...
/*0x001a*/ uint8_t                      PAD_align_001C[0x2];  // [LOW] Alignment pad 0x1A-0x1B. Not touched by InitBonusCache; gap before 0x1C int.
/*0x001c*/ int32_t                      ArmorClassBonus;  // [HIGH] InitBonusCache @ 0x140103D94 MOV [R8+0x1C], R9D (=0). Isolated dword write (not paired into qword).
/*0x0020*/ int32_t                      CurrWeight;  // [HIGH] InitBonusCache @ 0x140103FB4 MOV qword [R8+0x20], R9 (=0). Reader GetEnduranceRegen: (int)param_1[4] compared vs *(in...
/*0x0024*/ int32_t                      LastHitPointSendPercent;  // [HIGH] InitBonusCache upper half of 0x20 qword zero-write. No other writer/reader in scope; paired init is positive proof of...
/*0x0028*/ uint32_t                     LastManaPointSendPercent;  // [MEDIUM] STILL-SEARCHING: InitBonusCache does NOT zero +0x28 or +0x2C. Gap between +0x24 and +0x30. May init in a different pa...
/*0x002c*/ uint32_t                     LastEndurancePointSendPercent;  // [MEDIUM] STILL-SEARCHING: same gap as 0x28. Paired-slot candidate with 0x28. Type inferred from InitBonusCache dword-zero; nee...
/*0x0030*/ int32_t                      HPBonus;  // [HIGH] Init @ 0x140103FB8 MOV [R8+0x30], 0. Reader Max_HP @ 0x1400FFB9D MOVSXD RSI,[RBX+0x30] in bCapAtMax path; Cur_HP via ...
/*0x0034*/ int32_t                      ManaBonus;  // [HIGH] Init pairs with 0x30 qword. Reader Max_Mana @ 0x1402F7425 MOV EAX,[RBP+0x34] in bCapAtMax path.
/*0x0038*/ int32_t                      EnduranceBonus;  // [HIGH] Init @ 0x140103FBC. Reader Max_Endurance @ 0x1402F71CD MOV EAX,[R15+0x38] in bCapAtMax path.
/*0x003c*/ int32_t                      EnduranceCostPerSecond;  // [HIGH] Init paired with 0x38 qword. Upstream: EnduranceCostPerSecond. ASM alone confirms a 4-byte int lives here; no conflic...
/*0x0040*/ int32_t                      CombatEffectsBonus;  // [HIGH] Init @ 0x140103FC0 MOV qword [R8+0x40], 0.
/*0x0044*/ int32_t                      ShieldingBonus;  // [HIGH] Init upper half of 0x40 qword.
/*0x0048*/ int32_t                      SpellShieldBonus;  // [HIGH] Init @ 0x140103FC4 MOV qword [R8+0x48], 0.
/*0x004c*/ int32_t                      AvoidanceBonus;  // [HIGH] Init pair of 0x48 qword.
/*0x0050*/ int32_t                      AccuracyBonus;  // [HIGH] Init @ 0x140103FC8 MOV qword [R8+0x50], 0.
/*0x0054*/ int32_t                      StunResistBonus;  // [HIGH] Init pair of 0x50 qword.
/*0x0058*/ int32_t                      StrikeThroughBonus;  // [HIGH] Init @ 0x140103FCC MOV qword [R8+0x58], 0.
/*0x005c*/ int32_t                      DoTShieldBonus;  // [HIGH] Init pair of 0x58 qword.
/*0x0060*/ uint32_t                     DamageShieldMitigationBonus;  // [MEDIUM] STILL-SEARCHING: NOT zeroed in InitBonusCache (gap between +0x58 qword and +0x64 qword). Possibly init in a different...
/*0x0064*/ int32_t                      DamageShieldBonus;  // [HIGH] Init @ 0x140103FDE MOV qword [R8+0x64], 0.
/*0x0068*/ int32_t                      ItemSkillMinDamageMod[0];  // [HIGH] Upper half of 0x64 qword zero-write.
/*0x006c*/ int32_t                      ItemSkillMinDamageMod[1];  // [HIGH] Init @ 0x14010400C MOV qword [R8+0x6C], 0.
/*0x0070*/ int32_t                      ItemSkillMinDamageMod[2];  // [HIGH] Upper half of 0x6C qword.
/*0x0074*/ int32_t                      ItemSkillMinDamageMod[3];  // [HIGH] Init @ 0x140104017 MOV qword [R8+0x74], 0.
/*0x0078*/ int32_t                      ItemSkillMinDamageMod[4];  // [HIGH] Upper half of 0x74 qword (init pair).
/*0x007c*/ int32_t                      ItemSkillMinDamageMod[5];  // [HIGH] Init @ 0x140104022 MOV qword [R8+0x7C], 0.
/*0x0080*/ int32_t                      ItemSkillMinDamageMod[6];  // [HIGH] Upper half of 0x7C qword (init pair).
/*0x0084*/ int32_t                      ItemSkillMinDamageMod[7];  // [HIGH] Init @ 0x14010402D MOV qword [R8+0x84], 0.
/*0x0088*/ int32_t                      ItemSkillMinDamageMod[8];  // [HIGH] Upper half of 0x84 qword (init pair).
/*0x008c*/ int32_t                      SkillMinDamageModBonus[0];  // [HIGH] Init @ 0x140104005 MOV qword [R8+0x8C], 0.
/*0x0090*/ int32_t                      SkillMinDamageModBonus[1];  // [HIGH] Upper half of 0x8C qword (init pair).
/*0x0094*/ int32_t                      SkillMinDamageModBonus[2];  // [HIGH] Init @ 0x140104010.
/*0x0098*/ int32_t                      SkillMinDamageModBonus[3];  // [HIGH] Upper half of 0x94 qword (init pair).
/*0x009c*/ int32_t                      SkillMinDamageModBonus[4];  // [HIGH] Init @ 0x14010401B.
/*0x00a0*/ int32_t                      SkillMinDamageModBonus[5];  // [HIGH] Upper half of 0x9C qword (init pair).
/*0x00a4*/ int32_t                      SkillMinDamageModBonus[6];  // [HIGH] Init @ 0x140104026.
/*0x00a8*/ int32_t                      SkillMinDamageModBonus[7];  // [HIGH] Upper half of 0xA4 qword (init pair).
/*0x00ac*/ int32_t                      SkillMinDamageModBonus[8];  // [HIGH] Init @ 0x140104034 MOV dword [R8+0xAC], 0 (isolated dword -- end of array).
/*0x00b0*/ int32_t                      HeroicSTRBonus;  // [HIGH] Init @ 0x140103FE9 MOV qword [R8+0xB0], 0. Reader GetEnduranceRegen (int)param_1[0x16] = +0xB0 in encumbrance STR/AGI...
/*0x00b4*/ int32_t                      HeroicINTBonus;  // [HIGH] Init pair of 0xB0 qword. Reader GetManaRegen default branch *(int*)(this + 0xB4) for INT-caster classes. GetCurrentMo...
/*0x00b8*/ int32_t                      HeroicWISBonus;  // [HIGH] Init @ 0x140103FF0 MOV qword [R8+0xB8], 0. Reader GetManaRegen case-WIS (int)param_1[0x17] = +0xB8. GetCurrentMod con...
/*0x00bc*/ int32_t                      HeroicAGIBonus;  // [HIGH] Init pair of 0xB8 qword. Reader GetEnduranceRegen *(int*)(this + 0xBC). GetCurrentMod confirms.
/*0x00c0*/ int32_t                      HeroicDEXBonus;  // [HIGH] Init @ 0x140103FF7 MOV qword [R8+0xC0], 0. Reader GetEnduranceRegen (int)param_1[0x18] = +0xC0. GetCurrentMod confirms.
/*0x00c4*/ int32_t                      HeroicSTABonus;  // [HIGH] Init pair of 0xC0 qword. Reader Max_HP @ 0x1400FFCBE MOV EAX,[RBX+0xC4] then *10 (STA-to-HP). Reader GetEnduranceRege...
/*0x00c8*/ int32_t                      HeroicCHABonus;  // [HIGH] Init @ 0x140103FFE MOV dword [R8+0xC8], 0 (isolated dword -- end of Heroic block).
/*0x00cc*/ uint32_t                     HealAmountBonus;  // [MEDIUM] STILL-SEARCHING: NOT zeroed in InitBonusCache directly. Gap between 0xC8 dword and 0xD8 qword. Type/presence unconfir...
/*0x00d0*/ uint32_t                     SpellDamageBonus;  // [MEDIUM] STILL-SEARCHING: same 0xCC-0xD4 gap in InitBonusCache. Type inferred from InitBonusCache dword-zero; needs confirmati...
/*0x00d4*/ uint32_t                     ClairvoyanceBonus;  // [MEDIUM] STILL-SEARCHING: same 0xCC-0xD4 gap in InitBonusCache. Type inferred from InitBonusCache dword-zero; needs confirmati...
/*0x00d8*/ int32_t                      AttackBonus;  // [HIGH] Init @ 0x140103FD0 MOV qword [R8+0xD8], 0.
/*0x00dc*/ int32_t                      HPRegenBonus;  // [HIGH] Init pair of 0xD8 qword. Reader GetHPRegen *(int*)(this+0xDC) adds to regen.
/*0x00e0*/ int32_t                      ManaRegenBonus;  // [HIGH] Init @ 0x140103FD7 MOV qword [R8+0xE0], 0. Reader GetManaRegen param_1[0x1C] = +0xE0.
/*0x00e4*/ int32_t                      EnduranceRegenBonus;  // [HIGH] Init pair of 0xE0 qword. Reader GetEnduranceRegen *(int*)(this+0xE4).
/*0x00e8*/ int32_t                      AttackSpeed;  // [HIGH] Init @ 0x140103FE2 MOV qword [R8+0xE8], 0. Reader TotalEffect spa=0xB (haste) branch (int)param_1[0x1D] = +0xE8 when ...
/*0x00ec*/ int32_t                      NoBuffItemHitpointAdjustment;  // [HIGH] Init pair of 0xE8. Reader Max_HP @ 0x1400FFBB5 MOVSXD RSI,[RBX+0xEC] in non-bCapAtMax path.
/*0x00f0*/ int32_t                      NoBuffItemManaAdjustment;  // [HIGH] Init @ 0x14010403B MOV qword [R8+0xF0], 0. Reader Max_Mana @ 0x1402F7469 MOV EAX,[RBP+0xF0] non-bCapAtMax path.
/*0x00f4*/ int32_t                      NoBuffItemEnduranceAdjustment;  // [HIGH] Init pair of 0xF0. Reader Max_Endurance @ 0x1402F722D MOV EAX,[R15+0xF4] non-bCapAtMax path.
/*0x00f8*/ int32_t                      NoBuffItemBaseChanceProc;  // [HIGH] Init @ 0x140104042.
/*0x00fc*/ int32_t                      NoBuffItemMinDamageMod;  // [HIGH] Init pair of 0xF8 qword.
/*0x0100*/ int32_t                      NoBuffItemInnateSpellRune;  // [HIGH] Init @ 0x140104049.
/*0x0104*/ int32_t                      NoBuffItemAvoidance;  // [HIGH] Init pair of 0x100 qword.
/*0x0108*/ int32_t                      NoBuffItemToHit;  // [HIGH] Init @ 0x140104050.
/*0x010c*/ int32_t                      NoBuffItemResistStunChance;  // [HIGH] Init pair of 0x108 qword.
/*0x0110*/ int32_t                      NoBuffItemDotShieldingEffect;  // [HIGH] Init @ 0x140104057.
/*0x0114*/ int32_t                      NoBuffItemStrikeThroughChance;  // [HIGH] Init pair of 0x110 qword.
/*0x0118*/ int32_t                      NoBuffItemAttack;  // [HIGH] Init @ 0x14010405E.
/*0x011c*/ int32_t                      NoBuffItemHitPointRegen;  // [HIGH] Init pair of 0x118 qword.
/*0x0120*/ int32_t                      NoBuffItemManaRegen;  // [HIGH] Init @ 0x140104065.
/*0x0124*/ int32_t                      NoBuffItemEnduranceRegen;  // [HIGH] Init pair of 0x120 qword.
/*0x0128*/ int32_t                      NoBuffItemDamageShield;  // [HIGH] Init @ 0x14010406C MOV dword [R8+0x128], 0 (isolated dword).
/*0x012c*/ int32_t                      NoBuffItemDamageShieldMitigation;  // [HIGH] Writer: CZC bonus-cache rebuild FUN_140100420 @ 0x140101504 MOV [RDI+0x12C], R15D where R15D=[RDI+0x60] (ItemDamageSh...
/*0x0130*/ uint8_t                      unk_0130_byte_flag;  // [HIGH] NEW per-patch byte flag inserted between NoBuffItemDamageShieldMitigation (+0x12C) and NoBuffItemHaste (relocated to ...
/*0x0130*/ int32_t                      Unknown0x28b8;  // [MEDIUM] W26 upstream-ghost (2026-04-23): upstream canonical label at same offset as our `unk_0130_byte_flag`. Upstream claims...
/*0x0134*/ int32_t                      NoBuffItemHaste;  // [HIGH] RELOCATED from upstream +0x130 per CZC_field_hunt_NoBuffItemHaste.md. Reader: TotalEffect @ 0x1400E8D78 MOV EAX,[RDI+...
/*0x0138*/ int32_t                      NoBuffItemSkillMinDamageMod[0];  // [HIGH] CZC bonus-cache rebuild FUN_140100420 @ 0x14010151A MOV [RDI+0x138], EAX copies from +0x68 (ItemSkillMinDamageMod[0])...
/*0x013c*/ int32_t                      NoBuffItemSkillMinDamageMod[1];  // [HIGH] Rebuild FUN_140100420 @ 0x140101523 MOV [RDI+0x13C], EAX copies from +0x6C. Init @ 0x14010407A MOV qword [R8+0x13C], ...
/*0x0140*/ int32_t                      NoBuffItemSkillMinDamageMod[2];  // [HIGH] Rebuild FUN_140100420 @ 0x14010152C MOV [RDI+0x140], EAX copies from +0x70. Upper half of 0x13C qword init.
/*0x0144*/ int32_t                      NoBuffItemSkillMinDamageMod[3];  // [HIGH] Rebuild FUN_140100420 @ 0x140101535 MOV [RDI+0x144], EAX copies from +0x74. Init @ 0x140104081 MOV qword [R8+0x144], ...
/*0x0148*/ int32_t                      NoBuffItemSkillMinDamageMod[4];  // [HIGH] Rebuild FUN_140100420 @ 0x14010153E MOV [RDI+0x148], EAX copies from +0x78. Upper half of 0x144 qword init.
/*0x014c*/ int32_t                      NoBuffItemSkillMinDamageMod[5];  // [HIGH] Rebuild FUN_140100420 @ 0x140101547 MOV [RDI+0x14C], EAX copies from +0x7C. Init @ 0x140104088 MOV qword [R8+0x14C], ...
/*0x0150*/ int32_t                      NoBuffItemSkillMinDamageMod[6];  // [HIGH] Rebuild FUN_140100420 @ 0x140101553 MOV [RDI+0x150], EAX copies from +0x80. Upper half of 0x14C qword init.
/*0x0154*/ int32_t                      NoBuffItemSkillMinDamageMod[7];  // [HIGH] Rebuild FUN_140100420 @ 0x14010155F MOV [RDI+0x154], EAX copies from +0x84. Init @ 0x14010408F MOV qword [R8+0x154], ...
/*0x0158*/ int32_t                      NoBuffItemSkillMinDamageMod[8];  // [HIGH] Rebuild FUN_140100420 @ 0x14010156B MOV [RDI+0x158], EAX copies from +0x88. Upper half of 0x154 qword init covers +0x...
/*0x015c*/ uint8_t                      bOutputHpRegen;  // [HIGH] Upstream bool bOutputHpRegen. Position corrected to +0x15C after NoBuffItemHaste insertion at +0x134 shifted SkillMin...
/*0x015d*/ uint8_t                      bInvulnerable;  // [HIGH] Upstream bool bInvulnerable. Upper half of 0x15C word init. CZC::operator= @ 0x1400EF36A-0x1400EF376 byte copy confir...
/*0x015e*/ uint8_t                      bOnAVehicle;  // [HIGH] Upstream bool bOnAVehicle. InitBonusCache @ 0x14010409E MOV byte [R8+0x15E], 0 (1 byte, isolated write).
/*0x015f*/ uint8_t                      PAD_align_0160[0x1];  // [LOW] Alignment pad to 0x160 spellCache. Not touched.
/*0x0160*/ uint8_t                      spellCache[0x90];  // [HIGH] SpellCache sub-object begin. CZC ctor @ 0x1400E9F0F ADD RCX, 0x160; CALL 0x1406543A0 -- direct SpellCache ctor call o...
/*0x0168*/ uint8_t                      spellCache_isDirty;  // [HIGH] spellCache isDirty-like flag. Reader TotalEffect (char)param_1[0x2D] = +0x168. Writer: ResetCalculatedStats (FUN_1400...
/*0x0178*/ uint8_t                      spellCache_itemCacheDirty;  // [HIGH] spellCache itemCacheDirty flag. Readers GetManaRegen/GetHPRegen/GetEnduranceRegen check (char)param_1[0x2F] = +0x178 ...
/*0x0188*/ uint8_t                      spellCache_extra_flag;  // [HIGH] spellCache extra flag. Reader TotalEffect (char)param_1[0x31] = +0x188 conditional on whether item effects are included.
/*0x01f0*/ uint64_t                     DoomEffectsBySlot.vftable;  // [HIGH] HashListSet<int,128> vftable. CZC ctor @ 0x1400E9F2B MOV [RBX+0x1F0], 0x14088F6C8.
/*0x01f8*/ uint64_t                     DoomEffectsBySlot_field1;  // [HIGH] HashListSet internal field 1. Ctor @ 0x1400E9F34 MOV [RBX+0x1F8], 0. HashListSet continues past 0x200 with +0x200=0, ...
/*0x0200*/ uint64_t                     DoomEffectsBySlot_list_head;  // [HIGH] DoomEffectsBySlot (HashListSet<int,128>) list-head/MaxDynSize. CZC ctor @ 0x1400E9F41 MOV [RBX+0x200], RDI (=0). RBX=...
/*0x0208*/ uint64_t                     DoomEffectsBySlot_list_tail;  // [HIGH] DoomEffectsBySlot list-tail/Count. CZC ctor @ 0x1400E9F48 MOV [RBX+0x208], RDI (=0).
/*0x0210*/ uint8_t                      DoomEffectsBySlot_Table[0x400];  // [HIGH] Table[128] of 8B bucket pointers = 1024 bytes. CZC ctor @ 0x1400E9F4F memset(RBX+0x210, 0, 0x400). Reader FUN_140103C...
/*0x0610*/ uint32_t                     LastHitEval;  // [HIGH] uint32_t LastHitEval (cached game-tick of last hit-evaluation event). InitBonusCache @ 0x1401040AC-0x1401040B2: MOV R...
/*0x09b8*/
};

// SIZE_CHECK(CharacterZoneClient, 0x9b8);  // uncomment once integrated

} // namespace eqlib

