/*
 * GENERATED by tools/scripts/emit_eqlib_headers.py
 *
 * Struct:        CharacterBase
 * sizeof:        0x398
 * Field count:   90
 * Source:        cb_state_table.py
 *
 * This is a canonical reference dump of our Python registry for
 * CharacterBase. It is NOT the integration target -- the upstream
 * Krakty/eqlib:apr15-2026-live header carries inheritance chains,
 * method declarations, and aggregate type usages that this file does
 * not attempt to reproduce.
 *
 * Format matches upstream's `/*0xNNNN*/ type name;` convention so a
 * manual reviewer can diff the field list side-by-side. Confidence
 * and evidence columns are carried as end-of-line comments.
 */

#pragma once

#include <cstdint>

namespace eqlib {

class [[offsetcomments]] CharacterBase
{
public:

/*0x0000*/ uint64_t                     vftable;  // [HIGH] CB vftable. CB ctor @ 0x1406B4C94 MOV [RCX],RAX where RAX=0x140B00950.
/*0x0008*/ uint8_t                      ProfileManager[0x50];  // [HIGH] ProfileManager sub-object (upstream sizeof 0x50). CB ctor @ 0x1406B4C9B CALL 0x14069DA40 with rcx=this+8. Callee zero...
/*0x0058*/ uint64_t                     PersonaEquipmentSets.vftable;  // [HIGH] PersonaEquipmentSetSet vftable qword (first slot of the embedded PersonaEquipmentSets aggregate @ CB+0x58, sizeof 0x1...
/*0x0060*/ uint64_t                     PersonaEquipmentSets.root;  // [HIGH] PersonaEquipmentSetSet tree-root pointer (upstream: Node*). CB ctor @ 0x1406B4CA0 MOV [RDI+0x60], 0 (qword). Null-che...
/*0x0068*/ uint64_t                     PersonaEquipmentSets.size_and_pad;  // [HIGH] PersonaEquipmentSetSet { int size; int _pad; } tail qword. CB ctor @ 0x1406B4CBA MOV [RDI+0x68], 0 (qword). Cleared i...
/*0x0070*/ uint64_t                     languages_0_7;  // [HIGH] languages[0..7]. Sub-ctor @ 0x1406B75F2 MOV [RCX+0x70], 0 (qword). Upstream languages[MAX_LANGUAGES=32] maps to CB-re...
/*0x0078*/ uint64_t                     languages_8_15;  // [HIGH] languages[8..15]. Sub-ctor @ 0x1406B75F6 MOV [RCX+0x78], 0. Verified vs upstream d78e8ac.
/*0x0080*/ uint64_t                     languages_16_23;  // [HIGH] languages[16..23]. Sub-ctor @ 0x1406B75FA MOV [RCX+0x80], 0. Verified vs upstream d78e8ac.
/*0x0088*/ uint64_t                     languages_24_31;  // [HIGH] languages[24..31]. Sub-ctor @ 0x1406B7601 MOV [RCX+0x88], 0. Verified vs upstream d78e8ac.
/*0x0090*/ float                        X;  // [HIGH] Position X (float). Sub-ctor @ 0x1406B7549 MOV [RCX+0x90], 0 (qword covers X+Y).
/*0x0094*/ float                        Y;  // [HIGH] Position Y (float). Covered by qword write at CB+0x90.
/*0x0098*/ float                        Z;  // [HIGH] Position Z (float). Sub-ctor @ 0x1406B7552 MOV [RCX+0x98], 0 (qword covers Z+Heading).
/*0x009c*/ float                        Heading;  // [HIGH] Heading (float). Covered by qword write at CB+0x98.
/*0x00a0*/ char                         Name[0x40];  // [HIGH] Character Name (64-byte null-terminated string). CB ctor @ 0x1406B4CC4 MOV [RDI+0xA0], 0 sets terminator. Also touche...
/*0x00e0*/ char                         Lastname[0x20];  // [HIGH] Character Lastname (32-byte null-terminated string). CB ctor @ 0x1406B4CD1 MOV [RDI+0xE0], 0 sets terminator. Sub-cto...
/*0x0100*/ char                         Title[0x80];  // [HIGH] Character Title (128-byte null-terminated string). CB ctor @ 0x1406B4CD8 MOV [RDI+0x100], 0 sets terminator. Sub-ctor...
/*0x0180*/ char                         VehicleName[0x40];  // [HIGH] Vehicle Name (64-byte null-terminated string). CB ctor @ 0x1406B4CDF MOV [RDI+0x180], 0. Sub-ctor @ 0x1406B7581..0x14...
/*0x01c0*/ uint32_t                     Status;  // [HIGH] eCharacterStatus (dword). Sub-ctor @ 0x1406B756D MOV [RCX+0x1C0], 0 (byte, clears first byte of dword).
/*0x01c4*/ uint32_t                     currentZoneId;  // [HIGH] EQZoneIndex (dword). Sub-ctor @ 0x1406B7574 MOV [RCX+0x1C4], 0 (dword).
/*0x01c8*/ uint8_t                      standstate;  // [HIGH] standstate (byte). Sub-ctor @ 0x1406B757A MOV [RCX+0x1C8], 0 (byte).
/*0x01cc*/ uint8_t                      raidData_memsetted[0xd8];  // [HIGH] RaidData sub-struct head (0xD8 bytes via memset; last 4 bytes at +0x2A4 are a separate dword store -- see next entry)...
/*0x02a4*/ uint32_t                     raidData_tail_dword;  // [HIGH] Dword written immediately after the RaidData memset. CB ctor @ 0x1406B4CEE MOV [RDI+0x2A4], 0. Part of the RaidData s...
/*0x02a8*/ int64_t                      ExpansionFlags;  // [HIGH] int64_t ExpansionFlags. Sub-ctor @ 0x1406B759D MOV [RCX+0x2A8], 0 (qword).
/*0x02b0*/ uint8_t                      bSuperPKILL;  // [HIGH] bool bSuperPKILL. Sub-ctor @ 0x1406B75A4 MOV WORD [RCX+0x2B0], 0 (word covers bSuperPKILL+bUnclone).
/*0x02b1*/ uint8_t                      bUnclone;  // [HIGH] bool bUnclone. High byte of the CB+0x2B0 word-write.
/*0x02b2*/ uint8_t                      bDead;  // [HIGH] bool bDead. Sub-ctor @ 0x1406B75AB MOV BYTE [RCX+0x2B2], 0.
/*0x02b3*/ uint8_t                      PAD_align_02B4;  // [LOW] Alignment pad 0x2B3 -- not touched; gap before LD_Timer dword at 0x2B4.
/*0x02b4*/ int32_t                      LD_Timer;  // [HIGH] int LD_Timer. Sub-ctor @ 0x1406B75B2 MOV [RCX+0x2B4], 0 (qword covers LD_Timer+SpellInterruptCount).
/*0x02b8*/ int32_t                      SpellInterruptCount;  // [HIGH] int SpellInterruptCount. Covered by qword write at CB+0x2B4.
/*0x02bc*/ uint8_t                      bAutoSplit;  // [HIGH] bool bAutoSplit. Sub-ctor @ 0x1406B75B9 MOV WORD [RCX+0x2BC], 0x1 -- **DEFAULTS TRUE** (low byte=1). The word-write c...
/*0x02bd*/ uint8_t                      bTellsOff;  // [HIGH] bool bTellsOff. High byte of the CB+0x2BC word-write (=0).
/*0x02be*/ uint8_t                      bGmInvis;  // [HIGH] bool bGmInvis. Sub-ctor @ 0x1406B75C2 MOV BYTE [RCX+0x2BE], 0.
/*0x02bf*/ uint8_t                      PAD_align_02C0;  // [LOW] Alignment pad 0x2BF -- gap before KillMe dword at 0x2C0.
/*0x02c0*/ int32_t                      KillMe;  // [HIGH] int KillMe. Sub-ctor @ 0x1406B75C9 MOV [RCX+0x2C0], 0 (qword covers KillMe + 4 bool flags).
/*0x02c4*/ uint8_t                      CheaterLdFlag;  // [HIGH] bool CheaterLdFlag (likely SoulMarkCount int per upstream comment). Covered by qword at CB+0x2C0.
/*0x02c5*/ uint8_t                      NoRent;  // [HIGH] bool NoRent. Covered by qword at CB+0x2C0.
/*0x02c6*/ uint8_t                      Corpse;  // [HIGH] bool Corpse. Covered by qword at CB+0x2C0.
/*0x02c7*/ uint8_t                      ClientGmFlagSet;  // [HIGH] bool ClientGmFlagSet. Covered by qword at CB+0x2C0.
/*0x02c8*/ int32_t                      BankSharedPlat;  // [HIGH] int BankSharedPlat. Sub-ctor @ 0x1406B75DE MOV [RCX+0x2C8], 0 (qword covers BankSharedPlat+BankPlat).
/*0x02cc*/ int32_t                      BankPlat;  // [HIGH] int BankPlat. Covered by qword at CB+0x2C8.
/*0x02d0*/ int32_t                      BankGold;  // [HIGH] int BankGold. Sub-ctor @ 0x1406B75E5 MOV [RCX+0x2D0], 0 (qword covers BankGold+BankSilver).
/*0x02d4*/ int32_t                      BankSilver;  // [HIGH] int BankSilver. Covered by qword at CB+0x2D0.
/*0x02d8*/ int32_t                      BankCopper;  // [HIGH] int BankCopper. Sub-ctor @ 0x1406B75EC MOV [RCX+0x2D8], 0 (dword only).
/*0x02dc*/ int32_t                      Platinum;  // [HIGH] int Platinum. Sub-ctor @ 0x1406B75D0 MOV [RCX+0x2DC], 0 (qword, unaligned, covers Platinum+Gold).
/*0x02e0*/ int32_t                      Gold;  // [HIGH] int Gold. Covered by unaligned qword at CB+0x2DC.
/*0x02e4*/ int32_t                      Silver;  // [HIGH] int Silver. Sub-ctor @ 0x1406B75D7 MOV [RCX+0x2E4], 0 (qword covers Silver+Copper).
/*0x02e8*/ int32_t                      Copper;  // [HIGH] int Copper. Covered by qword at CB+0x2E4.
/*0x02ec*/ int32_t                      STR;  // [HIGH] int STR. Sub-ctor @ 0x1406B7608 MOV [RCX+0x2EC], 0 (qword covers STR+STA). PcClient ctor re-zeros via vbtable-indirec...
/*0x02f0*/ int32_t                      STA;  // [HIGH] int STA. Covered by qword at CB+0x2EC.
/*0x02f4*/ int32_t                      CHA;  // [HIGH] int CHA. InitBonusCache @ 0x140103D18 MOV [RDX+RCX*1+0x2F4], R9D (vbtable-indirect, R9D=0). Also sub-ctor @ 0x1406B76...
/*0x02f8*/ int32_t                      DEX;  // [HIGH] int DEX. InitBonusCache @ 0x140103D28. Sub-ctor qword at CB+0x2F4 covers. PcClient ctor re-zeros.
/*0x02fc*/ int32_t                      INT;  // [HIGH] int INT. InitBonusCache @ 0x140103D38. Sub-ctor @ 0x1406B7616 qword covers INT+AGI. PcClient ctor re-zeros.
/*0x0300*/ int32_t                      AGI;  // [HIGH] int AGI. InitBonusCache @ 0x140103D48. PcClient ctor re-zeros.
/*0x0304*/ int32_t                      WIS;  // [HIGH] int WIS. InitBonusCache @ 0x140103D58. PcClient ctor re-zeros.
/*0x0308*/ int32_t                      LCK;  // [HIGH] int LCK. InitBonusCache @ 0x140103D68. PcClient ctor re-zeros.
/*0x030c*/ int32_t                      SavePoison;  // [HIGH] int SavePoison. InitBonusCache @ 0x140103D78.
/*0x0310*/ int32_t                      SaveMagic;  // [HIGH] int SaveMagic. InitBonusCache @ 0x140103D88.
/*0x0314*/ int32_t                      SaveDisease;  // [HIGH] int SaveDisease. InitBonusCache @ 0x140103DCC.
/*0x0318*/ int32_t                      SaveCorruption;  // [HIGH] int SaveCorruption. InitBonusCache @ 0x140103D9C.
/*0x031c*/ int32_t                      SaveFire;  // [HIGH] int SaveFire. InitBonusCache @ 0x140103DDC.
/*0x0320*/ int32_t                      SaveCold;  // [HIGH] int SaveCold. InitBonusCache @ 0x140103DEC.
/*0x0324*/ int32_t                      SavePhysical;  // [HIGH] int SavePhysical. InitBonusCache @ 0x140103DBC.
/*0x0328*/ int32_t                      UncappedStr;  // [HIGH] int UncappedStr. InitBonusCache @ 0x140103DAC.
/*0x032c*/ int32_t                      UncappedSta;  // [HIGH] int UncappedSta. InitBonusCache @ 0x140103DFC.
/*0x0330*/ int32_t                      UncappedCha;  // [HIGH] int UncappedCha. InitBonusCache @ 0x140103EEC.
/*0x0334*/ int32_t                      UncappedDex;  // [HIGH] int UncappedDex. InitBonusCache @ 0x140103EFC.
/*0x0338*/ int32_t                      UncappedInt;  // [HIGH] int UncappedInt. InitBonusCache @ 0x140103F0C.
/*0x033c*/ int32_t                      UncappedAgi;  // [HIGH] int UncappedAgi. InitBonusCache @ 0x140103F1C.
/*0x0340*/ int32_t                      UncappedWis;  // [HIGH] int UncappedWis. InitBonusCache @ 0x140103F2C.
/*0x0344*/ int32_t                      UncappedResistPoison;  // [HIGH] int UncappedResistPoison. InitBonusCache @ 0x140103F3C.
/*0x0348*/ int32_t                      UncappedResistMagic;  // [HIGH] int UncappedResistMagic. InitBonusCache @ 0x140103F4C.
/*0x034c*/ int32_t                      UncappedResistDisease;  // [HIGH] int UncappedResistDisease. InitBonusCache @ 0x140103F8C.
/*0x0350*/ int32_t                      UncappedResistCorruption;  // [HIGH] int UncappedResistCorruption. InitBonusCache @ 0x140103F5C.
/*0x0354*/ int32_t                      UncappedResistFire;  // [HIGH] int UncappedResistFire. InitBonusCache @ 0x140103F9C.
/*0x0358*/ int32_t                      UncappedResistCold;  // [HIGH] int UncappedResistCold. InitBonusCache @ 0x140103FAC.
/*0x035c*/ int32_t                      UncappedResistPhysical;  // [HIGH] int UncappedResistPhysical. InitBonusCache @ 0x140103F7C.
/*0x0360*/ int32_t                      NoBuffStr;  // [HIGH] int NoBuffStr. InitBonusCache @ 0x140103F6C.
/*0x0364*/ int32_t                      NoBuffSta;  // [HIGH] int NoBuffSta. InitBonusCache @ 0x140103E0C.
/*0x0368*/ int32_t                      NoBuffCha;  // [HIGH] int NoBuffCha. InitBonusCache @ 0x140103E1C.
/*0x036c*/ int32_t                      NoBuffDex;  // [HIGH] int NoBuffDex. InitBonusCache @ 0x140103E2C.
/*0x0370*/ int32_t                      NoBuffInt;  // [HIGH] int NoBuffInt. InitBonusCache @ 0x140103E3C.
/*0x0374*/ int32_t                      NoBuffAgi;  // [HIGH] int NoBuffAgi. InitBonusCache @ 0x140103E4C.
/*0x0378*/ int32_t                      NoBuffWis;  // [HIGH] int NoBuffWis. InitBonusCache @ 0x140103E5C.
/*0x037c*/ int32_t                      NoBuffResistPoison;  // [HIGH] int NoBuffResistPoison. InitBonusCache @ 0x140103E6C.
/*0x0380*/ int32_t                      NoBuffResistMagic;  // [HIGH] int NoBuffResistMagic. InitBonusCache @ 0x140103EAC.
/*0x0384*/ int32_t                      NoBuffResistDisease;  // [HIGH] int NoBuffResistDisease. InitBonusCache @ 0x140103E7C.
/*0x0388*/ int32_t                      NoBuffResistCorruption;  // [HIGH] int NoBuffResistCorruption. InitBonusCache @ 0x140103EBC.
/*0x038c*/ int32_t                      NoBuffResistFire;  // [HIGH] int NoBuffResistFire. InitBonusCache @ 0x140103ECC.
/*0x0390*/ int32_t                      NoBuffResistCold;  // [HIGH] int NoBuffResistCold. InitBonusCache @ 0x140103E9C.
/*0x0394*/ int32_t                      NoBuffResistPhysical;  // [HIGH] int NoBuffResistPhysical. InitBonusCache @ 0x140103E8C.
/*0x0398*/
};

// SIZE_CHECK(CharacterBase, 0x398);  // uncomment once integrated

} // namespace eqlib

