/*
 * GENERATED by tools/scripts/emit_eqlib_headers.py
 *
 * Struct: CStrRep
 * sizeof: 0x18
 * Field count: 6
 * Source: cxstr_state_table.py
 *
 * This is a canonical reference dump of our Python registry for
 * CStrRep. It is NOT the integration target -- the upstream
 * Krakty/eqlib:apr15-2026-test header carries inheritance chains,
 * method declarations, and aggregate type usages that this file does
 * not attempt to reproduce.
 *
 * Format matches upstream's `/*0xNNNN*/ type name;` convention so a
 * manual reviewer can diff the field list side-by-side. Confidence
 * and evidence columns are carried as end-of-line comments.
 */

#pragma once

#include <cstdint>

namespace eqlib {

class [[offsetcomments]] CStrRep
{
public:

/*0x0000*/ uint32_t refCount; // [HIGH] std::atomic<int>. AllocRepNoLock @ 0x1405A374F MOV DWORD PTR [r8], 0x1. FreeRepNoLock uses atomic dec via 0x1406DECD8...
/*0x0004*/ uint32_t alloc; // [HIGH] Capacity in bytes (excluding the 0x18-byte header). AllocRepNoLock @ 0x1405A37A1 MOV DWORD PTR [rax+0x4], ebx (fallba...
/*0x0008*/ uint32_t length; // [HIGH] Current string length in bytes. AllocRepNoLock @ 0x1405A3747 MOV DWORD PTR [r8+0x8], ebp (=0 on init). All assign/app...
/*0x000c*/ uint32_t encoding; // [HIGH] EStringEncoding (0=Utf8, 1=Utf16). AllocRepNoLock @ 0x1405A374B MOV DWORD PTR [r8+0xc], edi (arg2).
/*0x0010*/ void* freeList; // [HIGH] CXFreeList* -- which free list bucket this rep belongs to. AllocRepNoLock @ 0x1405A3756 MOV QWORD PTR [r8+0x10], rsi ...
/*0x0018*/ char utf8[0x4]; // [HIGH] Primary C-union variant. Upstream d78e8ac CXStr.h:82-87 declares a C union with three members { char utf8[4]; Unicode...
/*0x0018*/
};

// SIZE_CHECK(CStrRep, 0x18); // uncomment once integrated

} // namespace eqlib

