/*
 * GENERATED by tools/scripts/emit_eqlib_headers.py
 *
 * Struct: CXStr
 * sizeof: 0x8
 * Field count: 1
 * Source: cxstr_state_table.py
 *
 * This is a canonical reference dump of our Python registry for
 * CXStr. It is NOT the integration target -- the upstream
 * Krakty/eqlib:apr15-2026-test header carries inheritance chains,
 * method declarations, and aggregate type usages that this file does
 * not attempt to reproduce.
 *
 * Format matches upstream's `/*0xNNNN*/ type name;` convention so a
 * manual reviewer can diff the field list side-by-side. Confidence
 * and evidence columns are carried as end-of-line comments.
 */

#pragma once

#include <cstdint>

namespace eqlib {

class [[offsetcomments]] CXStr
{
public:

/*0x0000*/ void* m_data; // [HIGH] CXStr only field. CStrRep* to ref-counted body, or nullptr for empty. CXStr copy ctor (CXStr.h:352-366) reads other.m...
/*0x0008*/
};

// SIZE_CHECK(CXStr, 0x8); // uncomment once integrated

} // namespace eqlib

