/*
 * GENERATED by tools/scripts/emit_eqlib_headers.py
 *
 * Struct:        EQ_Affect
 * sizeof:        0x98
 * Field count:   34
 * Source:        eq_affect_state_table.py
 *
 * This is a canonical reference dump of our Python registry for
 * EQ_Affect. It is NOT the integration target -- the upstream
 * Krakty/eqlib:apr15-2026-live header carries inheritance chains,
 * method declarations, and aggregate type usages that this file does
 * not attempt to reproduce.
 *
 * Format matches upstream's `/*0xNNNN*/ type name;` convention so a
 * manual reviewer can diff the field list side-by-side. Confidence
 * and evidence columns are carried as end-of-line comments.
 */

#pragma once

#include <cstdint>

namespace eqlib {

class [[offsetcomments]] EQ_Affect
{
public:

/*0x0000*/ int32_t                      SlotData[0].Slot;  // [HIGH] FUN_1406a9130 MOV EAX,dword [RCX+0x00] -> stack arg %d; 3 ctor sites (FUN_1400d8070, FUN_1400df080, FUN_1406b2e70) wr...
/*0x0004*/ uint8_t                      SlotData[0]._pad[0x4];  // [HIGH] 8-byte alignment pad before i64 Value. No reads, no writes.
/*0x0008*/ int64_t                      SlotData[0].Value;  // [HIGH] FUN_1406a9130 MOV RAX,qword [RCX+0x08] -> %lld; 3 ctor sites u64-zero at +0x08.
/*0x0010*/ int32_t                      SlotData[1].Slot;  // [HIGH] FUN_1406a9130 MOV EAX,dword [RCX+0x10] -> %d; ctor writes -1.
/*0x0014*/ uint8_t                      SlotData[1]._pad[0x4];  // [HIGH] 8-byte alignment pad.
/*0x0018*/ int64_t                      SlotData[1].Value;  // [HIGH] FUN_1406a9130 MOV RAX,qword [RCX+0x18] -> %lld; ctor u64-zero.
/*0x0020*/ int32_t                      SlotData[2].Slot;  // [HIGH] FUN_1406a9130 MOV EAX,dword [RCX+0x20] -> %d; ctor writes -1.
/*0x0024*/ uint8_t                      SlotData[2]._pad[0x4];  // [HIGH] 8-byte alignment pad.
/*0x0028*/ int64_t                      SlotData[2].Value;  // [HIGH] FUN_1406a9130 MOV RAX,qword [RCX+0x28] -> %lld; ctor u64-zero.
/*0x0030*/ int32_t                      SlotData[3].Slot;  // [HIGH] FUN_1406a9130 MOV EAX,dword [RCX+0x30] -> %d; ctor writes -1.
/*0x0034*/ uint8_t                      SlotData[3]._pad[0x4];  // [HIGH] 8-byte alignment pad.
/*0x0038*/ int64_t                      SlotData[3].Value;  // [HIGH] FUN_1406a9130 MOV RAX,qword [RCX+0x38] -> %lld; ctor u64-zero.
/*0x0040*/ int32_t                      SlotData[4].Slot;  // [HIGH] FUN_1406a9130 MOV EAX,dword [RCX+0x40] -> %d; ctor writes -1.
/*0x0044*/ uint8_t                      SlotData[4]._pad[0x4];  // [HIGH] 8-byte alignment pad.
/*0x0048*/ int64_t                      SlotData[4].Value;  // [HIGH] FUN_1406a9130 MOV RAX,qword [RCX+0x48] -> %lld; ctor u64-zero.
/*0x0050*/ int32_t                      SlotData[5].Slot;  // [HIGH] FUN_1406a9130 MOV EAX,dword [RCX+0x50] -> %d; ctor writes -1.
/*0x0054*/ uint8_t                      SlotData[5]._pad[0x4];  // [HIGH] 8-byte alignment pad.
/*0x0058*/ int64_t                      SlotData[5].Value;  // [HIGH] FUN_1406a9130 MOV RAX,qword [RCX+0x58] -> %lld; ctor u64-zero.
/*0x0060*/ uint64_t                     CasterGuid;  // [HIGH] EqGuid (u64). FUN_1406a9130 MOV RAX,qword [RCX+0x60] -> %llu. FindAffectSlot 0x1400dd74C reads qword [RDI+0x60] and p...
/*0x0068*/ uint32_t                     Flags;  // [HIGH] FUN_1406a9130 MOV EAX,dword [RCX+0x68] -> %u. 3 ctor sites write puVar[0x1A]=0. Bit semantics include bard-song indic...
/*0x006c*/ int32_t                      SpellID;  // [HIGH] FUN_1406a9130 MOV R10D,dword [RCX+0x6C] -> %d. GetPCSpellAffect 0x1400dee00 reads *(int*)(lVar+0x6C) as spell-id into...
/*0x0070*/ int32_t                      Duration;  // [HIGH] FUN_1406a9130 MOV R11D,dword [RCX+0x70] -> %d. Entry check: `-4` = empty-slot marker (skip serialization). Ctor: u64 ...
/*0x0074*/ int32_t                      InitialDuration;  // [HIGH] FUN_1406a9130 MOV EAX,dword [RCX+0x74] -> %d. Ctor: u64 write at +0x74 zeros InitialDuration+HitCount pair.
/*0x0078*/ int32_t                      HitCount;  // [HIGH] FUN_1406a9130 MOV EAX,dword [RCX+0x78] -> %d. Ctor: u64 write at +0x74 zeros this slot half.
/*0x007c*/ int32_t                      ViralTimer;  // [HIGH] FUN_1406a9130 MOV EAX,dword [RCX+0x7C] -> %d (last stack arg). 3 ctor sites write puVar[0x1F]=0.
/*0x0080*/ float                        Modifier;  // [HIGH] Default 1.0f. FUN_1406a9130 MOVSS XMM0,dword [RCX+0x80] -> %.*f (precision literal 3). 3 ctor sites u64-write 0x3f800...
/*0x0084*/ float                        Y;  // [MEDIUM] Ctor: u64 write at +0x80 zeros this (high 32 bits). No active accessor read in this pass. Upstream SPA 441 mechanics ...
/*0x0088*/ float                        X;  // [MEDIUM] Ctor: u64 write at +0x88 zeros this (low 32 bits; high 32 bits zero Z). No active accessor read in this pass. SPA 441...
/*0x008c*/ float                        Z;  // [MEDIUM] Ctor: u64 write at +0x88 zeros this (high 32 bits). No active accessor read in this pass. SPA 441 XYZ triple.
/*0x0090*/ uint8_t                      Type;  // [HIGH] UPSTREAM-NAMED Type but USED AS CASTER-LEVEL (W25 follow-up): FUN_1406a9130 MOVZX R9D,byte [RCX+0x90] -> printf 2nd %...
/*0x0091*/ uint8_t                      Level;  // [HIGH] UPSTREAM-NAMED Level. FUN_1406a9130 MOVZX R8D,byte [RCX+0x91] -> printf 1st %d. 3 ctor sites write *(u8*)((u8*)puVar+...
/*0x0092*/ uint8_t                      ChargesRemaining;  // [LOW] No active read/write in this pass. Upstream field declared. Serializer emits literal 0 at printf slot #3 (sourced fro...
/*0x0093*/ uint8_t                      Activatable;  // [LOW] No active read/write in this pass. Upstream field declared. Serializer emits literal 0 at printf slot #4 (placeholder...
/*0x0094*/ uint32_t                     Unknown0x64;  // [HIGH] Trailing 4-byte slot. Upstream Spells.h labels this `Unknown0x64` (u32). Binary evidence: no writes in any of 3 ctor ...
/*0x0098*/
};

// SIZE_CHECK(EQ_Affect, 0x98);  // uncomment once integrated

} // namespace eqlib

