/*
 * GENERATED by tools/scripts/emit_eqlib_headers.py
 *
 * Struct:        MActor
 * sizeof:        0x210
 * Field count:   111
 * Source:        mactor_state_table.py
 *
 * This is a canonical reference dump of our Python registry for
 * MActor. It is NOT the integration target -- the upstream
 * Krakty/eqlib:apr15-2026-live header carries inheritance chains,
 * method declarations, and aggregate type usages that this file does
 * not attempt to reproduce.
 *
 * Format matches upstream's `/*0xNNNN*/ type name;` convention so a
 * manual reviewer can diff the field list side-by-side. Confidence
 * and evidence columns are carried as end-of-line comments.
 */

#pragma once

#include <cstdint>

namespace eqlib {

class [[offsetcomments]] MActor
{
public:

/*0x0000*/ void*                        vftable;  // [HIGH] ActorBase_ctor_vtable_write
/*0x0008*/ int8_t                       TextureType;  // [HIGH] FUN_1402ff570_841938
/*0x0009*/ int8_t                       Material;  // [HIGH] FUN_1402ff570_841940
/*0x000a*/ int8_t                       Variation;  // [HIGH] FUN_1402ff570_841942
/*0x000b*/ int8_t                       HeadType;  // [HIGH] FUN_1402ff570_841944
/*0x000c*/ uint8_t                      FaceStyle;  // [HIGH] FUN_1402ff570_841946
/*0x000d*/ uint8_t                      HairColor;  // [HIGH] FUN_1402ff570_841948
/*0x000e*/ uint8_t                      FacialHairColor;  // [HIGH] FUN_1402ff570_841950
/*0x000f*/ uint8_t                      EyeColor1;  // [HIGH] FUN_1402ff570_841952
/*0x0010*/ uint8_t                      EyeColor2;  // [HIGH] FUN_1402ff570_841954
/*0x0011*/ uint8_t                      HairStyle;  // [HIGH] FUN_1402ff570_841956
/*0x0012*/ uint8_t                      FacialHair;  // [HIGH] FUN_1402ff570_841958
/*0x0013*/ uint8_t                      PAD_align_014[0x1];  // [PAD] declared_align_pad
/*0x0014*/ int32_t                      Race;  // [HIGH] FUN_1402ff570_841960_and_registry_DisplayRace
/*0x0018*/ int32_t                      RaceOverride;  // [HIGH] FUN_1402ff570_841962
/*0x001c*/ int32_t                      Class;  // [HIGH] FUN_1402ff570_841964_and_InitPZCFields_store28
/*0x0020*/ uint8_t                      Gender;  // [HIGH] FUN_1402ff570_841966_and_InitPZCFields_store30
/*0x0021*/ char                         ActorDef[0x40];  // [HIGH] FUN_1402ff570_841968_841995_64byte_copies
/*0x0061*/ uint8_t                      PAD_align_064[0x3];  // [PAD] declared_align_pad
/*0x0064*/ uint32_t                     ArmorColor_Head;  // [HIGH] FUN_1402ff570_842096_and_registry_TintArray0_verified_vs_upstream_d78e8ac
/*0x0068*/ uint32_t                     ArmorColor_Chest;  // [HIGH] FUN_1402ff570_842098
/*0x006c*/ uint32_t                     ArmorColor_Arms;  // [HIGH] FUN_1402ff570_842100
/*0x0070*/ uint32_t                     ArmorColor_Wrists;  // [HIGH] FUN_1402ff570_842102
/*0x0074*/ uint32_t                     ArmorColor_Hands;  // [HIGH] FUN_1402ff570_842104
/*0x0078*/ uint32_t                     ArmorColor_Legs;  // [HIGH] FUN_1402ff570_842106
/*0x007c*/ uint32_t                     ArmorColor_Feet;  // [HIGH] FUN_1402ff570_842108
/*0x0080*/ uint32_t                     ArmorColor_Primary;  // [HIGH] FUN_1402ff570_842110
/*0x0084*/ uint32_t                     ArmorColor_Offhand;  // [HIGH] FUN_1402ff570_842112
/*0x0088*/ uint8_t                      bShowHelm;  // [HIGH] FUN_1402ff570_842114_and_InitPZCFields_store63_init1
/*0x0089*/ uint8_t                      PAD_align_08C[0x3];  // [PAD] declared_align_pad
/*0x008c*/ int32_t                      Heritage;  // [HIGH] FUN_1402ff570_842116
/*0x0090*/ int32_t                      Tattoo;  // [HIGH] FUN_1402ff570_842118
/*0x0094*/ int32_t                      Details;  // [HIGH] FUN_1402ff570_842120
/*0x0098*/ uint32_t                     ActorEquipment_Head_type;  // [HIGH] FUN_1402ff570_842122_xmm_d0_verified_vs_upstream_d78e8ac
/*0x009c*/ uint32_t                     ActorEquipment_Head_variation;  // [HIGH] FUN_1402ff570_842122_xmm_d1
/*0x00a0*/ uint32_t                     ActorEquipment_Head_material;  // [HIGH] FUN_1402ff570_842122_xmm_d2
/*0x00a4*/ uint32_t                     ActorEquipment_Head_newArmorID;  // [HIGH] FUN_1402ff570_842122_xmm_d3
/*0x00a8*/ uint32_t                     ActorEquipment_Head_newArmorType;  // [HIGH] FUN_1402ff570_842124
/*0x00ac*/ uint32_t                     ActorEquipment_Chest_type;  // [HIGH] FUN_1402ff570_842126_xmm_d0
/*0x00b0*/ uint32_t                     ActorEquipment_Chest_variation;  // [HIGH] FUN_1402ff570_842126_xmm_d1
/*0x00b4*/ uint32_t                     ActorEquipment_Chest_material;  // [HIGH] FUN_1402ff570_842126_xmm_d2
/*0x00b8*/ uint32_t                     ActorEquipment_Chest_newArmorID;  // [HIGH] FUN_1402ff570_842126_xmm_d3
/*0x00bc*/ uint32_t                     ActorEquipment_Chest_newArmorType;  // [HIGH] FUN_1402ff570_842128
/*0x00c0*/ uint32_t                     ActorEquipment_Arms_type;  // [HIGH] FUN_1402ff570_842130_xmm_d0
/*0x00c4*/ uint32_t                     ActorEquipment_Arms_variation;  // [HIGH] FUN_1402ff570_842130_xmm_d1
/*0x00c8*/ uint32_t                     ActorEquipment_Arms_material;  // [HIGH] FUN_1402ff570_842130_xmm_d2
/*0x00cc*/ uint32_t                     ActorEquipment_Arms_newArmorID;  // [HIGH] FUN_1402ff570_842130_xmm_d3
/*0x00d0*/ uint32_t                     ActorEquipment_Arms_newArmorType;  // [HIGH] FUN_1402ff570_842132
/*0x00d4*/ uint32_t                     ActorEquipment_Wrists_type;  // [HIGH] FUN_1402ff570_842134_xmm_d0
/*0x00d8*/ uint32_t                     ActorEquipment_Wrists_variation;  // [HIGH] FUN_1402ff570_842134_xmm_d1
/*0x00dc*/ uint32_t                     ActorEquipment_Wrists_material;  // [HIGH] FUN_1402ff570_842134_xmm_d2
/*0x00e0*/ uint32_t                     ActorEquipment_Wrists_newArmorID;  // [HIGH] FUN_1402ff570_842134_xmm_d3
/*0x00e4*/ uint32_t                     ActorEquipment_Wrists_newArmorType;  // [HIGH] FUN_1402ff570_842136
/*0x00e8*/ uint32_t                     ActorEquipment_Hands_type;  // [HIGH] FUN_1402ff570_842138_xmm_d0
/*0x00ec*/ uint32_t                     ActorEquipment_Hands_variation;  // [HIGH] FUN_1402ff570_842138_xmm_d1
/*0x00f0*/ uint32_t                     ActorEquipment_Hands_material;  // [HIGH] FUN_1402ff570_842138_xmm_d2
/*0x00f4*/ uint32_t                     ActorEquipment_Hands_newArmorID;  // [HIGH] FUN_1402ff570_842138_xmm_d3
/*0x00f8*/ uint32_t                     ActorEquipment_Hands_newArmorType;  // [HIGH] FUN_1402ff570_842140
/*0x00fc*/ uint32_t                     ActorEquipment_Legs_type;  // [HIGH] FUN_1402ff570_842142_xmm_d0
/*0x0100*/ uint32_t                     ActorEquipment_Legs_variation;  // [HIGH] FUN_1402ff570_842142_xmm_d1
/*0x0104*/ uint32_t                     ActorEquipment_Legs_material;  // [HIGH] FUN_1402ff570_842142_xmm_d2
/*0x0108*/ uint32_t                     ActorEquipment_Legs_newArmorID;  // [HIGH] FUN_1402ff570_842142_xmm_d3
/*0x010c*/ uint32_t                     ActorEquipment_Legs_newArmorType;  // [HIGH] FUN_1402ff570_842144
/*0x0110*/ uint32_t                     ActorEquipment_Feet_type;  // [HIGH] FUN_1402ff570_842146_xmm_d0
/*0x0114*/ uint32_t                     ActorEquipment_Feet_variation;  // [HIGH] FUN_1402ff570_842146_xmm_d1
/*0x0118*/ uint32_t                     ActorEquipment_Feet_material;  // [HIGH] FUN_1402ff570_842146_xmm_d2
/*0x011c*/ uint32_t                     ActorEquipment_Feet_newArmorID;  // [HIGH] FUN_1402ff570_842146_xmm_d3
/*0x0120*/ uint32_t                     ActorEquipment_Feet_newArmorType;  // [HIGH] FUN_1402ff570_842148
/*0x0124*/ uint32_t                     ActorEquipment_Primary_type;  // [HIGH] FUN_1402ff570_842150_xmm_d0
/*0x0128*/ uint32_t                     ActorEquipment_Primary_variation;  // [HIGH] FUN_1402ff570_842150_xmm_d1
/*0x012c*/ uint32_t                     ActorEquipment_Primary_material;  // [HIGH] FUN_1402ff570_842150_xmm_d2
/*0x0130*/ uint32_t                     ActorEquipment_Primary_newArmorID;  // [HIGH] FUN_1402ff570_842150_xmm_d3
/*0x0134*/ uint32_t                     ActorEquipment_Primary_newArmorType;  // [HIGH] FUN_1402ff570_842152
/*0x0138*/ uint32_t                     ActorEquipment_Offhand_type;  // [HIGH] FUN_1402ff570_842154_xmm_d0
/*0x013c*/ uint32_t                     ActorEquipment_Offhand_variation;  // [HIGH] FUN_1402ff570_842154_xmm_d1
/*0x0140*/ uint32_t                     ActorEquipment_Offhand_material;  // [HIGH] FUN_1402ff570_842154_xmm_d2
/*0x0144*/ uint32_t                     ActorEquipment_Offhand_newArmorID;  // [HIGH] FUN_1402ff570_842154_xmm_d3
/*0x0148*/ uint32_t                     ActorEquipment_Offhand_newArmorType;  // [HIGH] FUN_1402ff570_842156
/*0x014c*/ uint8_t                      PAD_align_150[0x4];  // [PAD] ActorBase_tail_align_to_subclass_boundary
/*0x0150*/ int32_t                      LeftEyeMaterialIndex;  // [HIGH] FUN_1402ff900_842175
/*0x0154*/ int32_t                      RightEyeMaterialIndex;  // [HIGH] FUN_1402ff900_842177
/*0x0158*/ void*                        pParticlePoints_0;  // [HIGH] FUN_1402ff900_842179
/*0x0160*/ void*                        pParticlePoints_1;  // [HIGH] FUN_1402ff900_842181
/*0x0168*/ void*                        pParticlePoints_2;  // [HIGH] FUN_1402ff900_842183
/*0x0170*/ void*                        pParticlePoints_3;  // [HIGH] FUN_1402ff900_842185
/*0x0178*/ void*                        pParticlePoints_4;  // [HIGH] FUN_1402ff900_842187
/*0x0180*/ void*                        pParticlePoints_5;  // [HIGH] FUN_1402ff900_842189
/*0x0188*/ void*                        pParticlePoints_6;  // [HIGH] FUN_1402ff900_842191
/*0x0190*/ void*                        pParticlePoints_7;  // [HIGH] FUN_1402ff900_842193
/*0x0198*/ void*                        pParticlePoints_8;  // [HIGH] FUN_1402ff900_842195
/*0x01a0*/ void*                        pParticlePoints_9;  // [HIGH] FUN_1402ff900_842197
/*0x01a8*/ void*                        pLowerBones;  // [HIGH] FUN_1402ff900_842199
/*0x01b0*/ void*                        pUpperBones;  // [HIGH] FUN_1402ff900_842201
/*0x01b8*/ void*                        pActor;  // [HIGH] FUN_1402ff900_842203
/*0x01c0*/ void*                        pLight;  // [HIGH] FUN_1402ff900_842205
/*0x01c8*/ void*                        pActorAnimation;  // [HIGH] FUN_1402ff900_842207
/*0x01d0*/ void*                        StageInstances_pHead;  // [HIGH] FUN_1402ff900_842209_xmm_lo
/*0x01d8*/ void*                        StageInstances_pTail;  // [HIGH] FUN_1402ff900_842209_xmm_hi
/*0x01e0*/ uint8_t                      bActiveTransition;  // [HIGH] FUN_1402ff900_842211
/*0x01e1*/ uint8_t                      PAD_align_1E4[0x3];  // [PAD] declared_align_pad
/*0x01e4*/ uint32_t                     CurrentStage;  // [HIGH] FUN_1402ff900_842213
/*0x01e8*/ float                        ZOffset;  // [HIGH] FUN_1402ff900_842215
/*0x01ec*/ float                        AdjustedLoc_x;  // [HIGH] FUN_1402ff900_842217
/*0x01f0*/ float                        AdjustedLoc_y;  // [HIGH] FUN_1402ff900_842219
/*0x01f4*/ float                        AdjustedLoc_z;  // [HIGH] FUN_1402ff900_842221
/*0x01f8*/ uint8_t                      bReplacedStaticObject;  // [HIGH] FUN_1402ff900_842223
/*0x01f9*/ uint8_t                      PAD_align_1FC[0x3];  // [PAD] declared_align_pad
/*0x01fc*/ int32_t                      PartialFaceNumber;  // [HIGH] FUN_1402ff900_842225
/*0x0200*/ uint8_t                      bNewArmorDisabled;  // [HIGH] FUN_1402ff900_842227
/*0x0201*/ uint8_t                      PAD_align_208[0x7];  // [PAD] declared_align_pad
/*0x0208*/ void*                        pApplicationData;  // [HIGH] FUN_1402ff900_842229
/*0x0210*/
};

// SIZE_CHECK(MActor, 0x210);  // uncomment once integrated

} // namespace eqlib

