/*
 * GENERATED by tools/scripts/emit_eqlib_headers.py
 *
 * Struct:        PcClient
 * sizeof:        0x3298
 * Field count:   231
 * Source:        pcclient_state_table.py
 *
 * This is a canonical reference dump of our Python registry for
 * PcClient. It is NOT the integration target -- the upstream
 * Krakty/eqlib:apr15-2026-live header carries inheritance chains,
 * method declarations, and aggregate type usages that this file does
 * not attempt to reproduce.
 *
 * Format matches upstream's `/*0xNNNN*/ type name;` convention so a
 * manual reviewer can diff the field list side-by-side. Confidence
 * and evidence columns are carried as end-of-line comments.
 */

#pragma once

#include <cstdint>

namespace eqlib {

class [[offsetcomments]] PcClient
{
public:

/*0x0010*/ int[10]                      RecentTasks[10];  // [HIGH-VALIDATED] state-reset writes 0x10..0x30 qword zeros
/*0x0038*/ PCTaskStatus[1]              Tasks[1];  // [HIGH-VALIDATED] state-reset 0x38..0xa0 zeroed
/*0x00a8*/ PCTaskStatus[29]             Quests[29];  // [HIGH-VALIDATED] state-reset loop 29 × 0x70 bytes at 0xb0..
/*0x0d58*/ uint8_t[800]                 BitFlags;  // [HIGH-VALIDATED] state-reset byte-loop 0x640 bytes
/*0x1078*/ BenefitSelection[5]          ActiveTributeBenefits;  // [STILL-SEARCHING] not in ctor nor state-reset
/*0x10a0*/ BenefitSelection[10]         ActiveTrophyTributeBenefits;  // [STILL-SEARCHING] not in ctor nor state-reset
/*0x10f0*/ uint8_t[800]                 BitFlags2;  // [OFFSET-MOVED] header lists uint8_t[800] 0x10f0..0x1410; state-reset writes ItemIndex pattern (0xffffffff/0 pairs) at 0x1398..0x1408...
/*0x1410*/ ItemContainer                BankItems;  // [HIGH-VALIDATED] PcBase ctor Init(0x18,1,0)
/*0x1438*/ ItemContainer                SharedBankItems;  // [HIGH-VALIDATED] ctor Init(0x8,2,0)
/*0x1460*/ ItemContainer                OverflowBufferItems;  // [HIGH-VALIDATED] ctor Init(0,0x29,1)
/*0x1488*/ ItemContainer                LimboBufferItems;  // [HIGH-VALIDATED] ctor Init(0x24,5,0)
/*0x14b0*/ ItemContainer                MercenaryItems;  // [HIGH-VALIDATED] ctor Init(4,0x19,0)
/*0x14d8*/ ItemContainer                MountKeyRingItems;  // [HIGH-VALIDATED] ctor Init(500,0x1b,0)
/*0x1500*/ ItemContainer                IllusionKeyRingItems;  // [HIGH-VALIDATED] ctor Init(300,0x1d,0)
/*0x1528*/ ItemContainer                FamiliarKeyRingItems;  // [HIGH-VALIDATED] ctor Init(0x1c2,0x1f,0)
/*0x1550*/ ItemContainer                HeroForgeKeyRingItems;  // [HIGH-VALIDATED] ctor Init(1000,0x21,0)
/*0x1578*/ ItemContainer                TeleportationKeyRingItems;  // [HIGH-VALIDATED] ctor Init(0xfa,0x23,0)
/*0x15a0*/ ItemContainer                DragonHoardItems;  // [HIGH-VALIDATED] ctor Init(0,0x2a,1)
/*0x15c8*/ SoeUtil::HashMap<int, ItemPtr> PersonalTradeskillDepotItems;  // [HIGH-VALIDATED] ctor: vftable 0x1408f3290 + zeros + sentinel -1 at +0x15f8. \| W26 name-canonical (2026-04-23): type string promoted ...
/*0x1600*/ ItemContainer                ActivatedKeyRingItems;  // [HIGH-VALIDATED] ctor Init(500,0x25,0)
/*0x1628*/ ItemContainer                EquipmentKeyRingItems;  // [HIGH-VALIDATED] ctor Init(1000,0x27,0)
/*0x1650*/ ItemContainer                AltStorageItems;  // [HIGH-VALIDATED] ctor Init(0,0x13,1)
/*0x1678*/ ItemContainer                ArchivedDeletedItems;  // [HIGH-VALIDATED] ctor Init(0,0x14,1)
/*0x16a0*/ ItemContainer                MailItems;  // [HIGH-VALIDATED] ctor Init(0,0x15,1)
/*0x16c8*/ MailItemsHash                MailItemsData;  // [HIGH-VALIDATED] ctor alloc 0x33-prime hashmap
/*0x16e0*/ eqtime_t[1]                  RecentMoves[1];  // [HIGH-VALIDATED] state-reset u64@+0x16e0=0
/*0x16e8*/ HashTable<DynamicZoneData>   CurrentDynamicZones;  // [HIGH-VALIDATED] state-reset FUN_1402dd520(+0x16e8). \| W26 name-canonical (2026-04-23): type string promoted from HashTable<DZData> t...
/*0x1700*/ HashTable<int>               LearnedRecipes;  // [HIGH-VALIDATED] ctor FUN_14008f510(+0x1700,0x100)
/*0x1718*/ EQList<TSRC*>                QualifyingRecipeCounts;  // [HIGH-VALIDATED] ctor vftable 0x14089bae8 at +0x1718
/*0x1738*/ HashTable<int>               NonrepeatableQuests;  // [HIGH-VALIDATED] ctor FUN_14008f510(+0x1738,0x100)
/*0x1750*/ HashTable<int>               CompletedTasks;  // [HIGH-VALIDATED] ctor FUN_14008f510(+0x1750,0x100)
/*0x1768*/ HashTable<int>               CompletedTasks2;  // [HIGH-VALIDATED] ctor FUN_14008f510(+0x1768,0x100)
/*0x1780*/ eqtime_t                     AlchemyTimestamp;  // [HIGH-VALIDATED] falls in zero-fill block
/*0x1788*/ bool                         bWhat;  // [HIGH-VALIDATED] ctor byte@+0x1788=0
/*0x1789*/ bool                         bSomethingHome;  // [HIGH-VALIDATED] padding byte
/*0x178c*/ uint32_t                     LoginTime;  // [HIGH-VALIDATED] state-reset u32@+0x178c=0
/*0x1790*/ EqGuid                       GuildID;  // [HIGH-VALIDATED] state-reset u64@+0x1790=0
/*0x1798*/ EqGuid                       FellowshipID;  // [HIGH-VALIDATED] state-reset u64@+0x1798=0
/*0x17a0*/ SFellowship*                 pFellowship;  // [HIGH-VALIDATED] ctor qword@+0x17a0=0
/*0x17a8*/ bool                         GuildShowSprite;  // [HIGH-VALIDATED] state-reset byte@+0x17a8=0
/*0x17b0*/ eqtime_t                     CreationTime;  // [HIGH-VALIDATED] ctor Util__FastTime -> +0x17b0
/*0x17b8*/ eqtime_t                     AccountCreationTime;  // [HIGH-VALIDATED] ctor Util__FastTime -> +0x17b8
/*0x17c0*/ eqtime_t                     LastPlayedTime;  // [HIGH-VALIDATED] state-reset u64@+0x17c0=0
/*0x17c8*/ uint32_t                     MinutesPlayed;  // [HIGH-VALIDATED] state-reset u32@+0x17c8=0
/*0x17cc*/ uint8_t                      Anonymous;  // [HIGH-VALIDATED] state-reset u16@+0x17cc=0
/*0x17cd*/ bool                         bGM;  // [HIGH-VALIDATED] part of u16 at 0x17cc
/*0x17ce*/ bool                         bGMStealth;  // [HIGH-VALIDATED] state-reset byte@+0x17ce=0
/*0x17d0*/ int                          AirSupply;  // [HIGH-VALIDATED] state-reset u64@+0x17d0=0 (pair w/SerialNum); 33 live xrefs
/*0x17d4*/ uint32_t                     SerialNum;  // [HIGH-VALIDATED] part of u64@0x17d0
/*0x17d8*/ bool                         bNewCharacter;  // [HIGH-VALIDATED] state-reset byte@+0x17d8=0
/*0x17dc*/ int                          TasksAssigned;  // [HIGH-VALIDATED] state-reset u64@+0x17dc=0
/*0x17e0*/ int                          TasksCompleted;  // [HIGH-VALIDATED] part of u64 pair
/*0x17e4*/ long                         TaskRequestTimer;  // [HIGH-VALIDATED] state-reset u64@+0x17e4=0
/*0x17e8*/ uint32_t                     UniquePlayerID;  // [HIGH-VALIDATED] state-reset covers pair; note PcProfile+0x17e8 distinct
/*0x17ec*/ WorldLocation                DynamicZoneSafeReturnLocation;  // [HIGH-VALIDATED] state-reset u32@+0x17ec=0; PROFILE at +0x17ec stores Max_Mana
/*0x1800*/ DynamicZoneTimerData*        pDZTimerRoot;  // [HIGH-VALIDATED] state-reset walks list, null-out
/*0x1808*/ int                          BenefitTimer;  // [HIGH-VALIDATED] state-reset u64@+0x1808=-1
/*0x180c*/ int                          TrophyBenefitTimer;  // [HIGH-VALIDATED] part of u64@0x1808
/*0x1810*/ int64_t                      CareerFavor;  // [HIGH-VALIDATED] state-reset u64@+0x1810=0
/*0x1818*/ int64_t                      CurrFavor;  // [HIGH-VALIDATED] state-reset u64@+0x1818=0
/*0x1820*/ bool                         bBenefitsActive;  // [HIGH-VALIDATED] state-reset u16@+0x1820=0
/*0x1821*/ bool                         bTrophyBenefitsActive;  // [HIGH-VALIDATED] part of u16
/*0x1822*/ bool                         bHasResetStartingCity;  // [HIGH-VALIDATED] state-reset byte@+0x1822=0
/*0x1824*/ int                          PvPKills;  // [HIGH-VALIDATED] state-reset u64@+0x1824=0
/*0x1828*/ int                          PvPDeaths;  // [HIGH-VALIDATED] part of pair
/*0x182c*/ int                          PvPCurrentPoints;  // [HIGH-VALIDATED] state-reset u64@+0x182c=0
/*0x1830*/ int                          PvPTotalPointsEarned;  // [HIGH-VALIDATED] part
/*0x1834*/ int                          PvPKillStreak;  // [HIGH-VALIDATED] state-reset u64@+0x1834=0
/*0x1838*/ int                          PvPDeathStreak;  // [HIGH-VALIDATED] part
/*0x183c*/ int                          PvPCurrentStreak;  // [HIGH-VALIDATED] state-reset u32@+0x183c=0
/*0x1840*/ PvPKill                      LastKill;  // [HIGH-VALIDATED] PcBase ctor: XMM0 MOVUPS 0x1840..0x1870 + 4 u64 zeros to 0x1898
/*0x18a0*/ PvPDeath                     LastDeath;  // [HIGH-VALIDATED] state-reset u64 writes 0x18a0..0x18f0
/*0x18f8*/ HashTable<PvPKill24HourData> PvPLast24HoursKillHash;  // [HIGH-VALIDATED] ctor FUN_14020a700(+0x18f8) + alloc prime hash. \| W26 name-canonical (2026-04-23): type string promoted from HashTab...
/*0x1910*/ int                          PvPInfamyLevel;  // [HIGH-VALIDATED] state-reset u64@+0x1910=0
/*0x1914*/ int                          PvPVitality;  // [HIGH-VALIDATED] part
/*0x1918*/ eqtime_t                     PvPLastInfamyTime;  // [HIGH-VALIDATED] state-reset u32@+0x1918=0
/*0x1920*/ eqtime_t                     LastLastNameChange;  // [HIGH-VALIDATED] state-reset u64@+0x1920=0
/*0x1928*/ int                          LastNameChangePriv;  // [HIGH-VALIDATED] state-reset u64@+0x1928=1
/*0x192c*/ uint32_t                     PvPLastVitalityTime;  // [STILL-SEARCHING] coalesced writes hide isolation
/*0x1930*/ int                          GoodPointsAvailable;  // [HIGH-VALIDATED] state-reset u64@+0x1930=0 (alias RadiantCrystals)
/*0x1934*/ int                          GoodTotalPointsEarned;  // [HIGH-VALIDATED] part
/*0x1938*/ int                          EvilPointsAvailable;  // [HIGH-VALIDATED] state-reset u64@+0x1938=0 (alias EbonCrystals)
/*0x193c*/ int                          EvilTotalPointsEarned;  // [HIGH-VALIDATED] part
/*0x1940*/ bool                         bCanRequestNameChange;  // [HIGH-VALIDATED] state-reset u32@+0x1940=0
/*0x1941*/ bool                         bCanRequestNameChange2;  // [HIGH-VALIDATED] packed
/*0x1942*/ bool                         bCanRequestServerTransfer;  // [HIGH-VALIDATED] packed
/*0x1943*/ bool                         bIsCopied;  // [HIGH-VALIDATED] packed
/*0x1948*/ eqtime_t                     ServerTransferGrantTime;  // [HIGH-VALIDATED] state-reset u64@+0x1948=0
/*0x1950*/ bool                         bCanRequestRaceChange;  // [HIGH-VALIDATED] state-reset byte@+0x1950=0
/*0x1954*/ uint32_t                     LastAAResetTime;  // [HIGH-VALIDATED] state-reset u64@+0x1954=0
/*0x1958*/ uint32_t                     LastMercAAResetTime;  // [HIGH-VALIDATED] part
/*0x195c*/ EQZoneIndex                  NewZoneID;  // [HIGH-VALIDATED] state-reset u32@+0x195c=0
/*0x1960*/ int                          NewAreaID;  // [HIGH-VALIDATED] state-reset u64@+0x1960=-1
/*0x1964*/ EAreaCorner                  eNewAreaCorner;  // [HIGH-VALIDATED] part
/*0x1968*/ EQZoneIndex                  PreviousZoneID;  // [HIGH-VALIDATED] state-reset u64@+0x1968=0
/*0x196c*/ int                          RealEstateZoneID;  // [HIGH-VALIDATED] part
/*0x1970*/ char                         ServerCreated[0x20];  // [HIGH-VALIDATED] state-reset 4x u64@+0x1970..+0x198f
/*0x1990*/ PCAdventureData              AdventureData;  // [HIGH-VALIDATED] state-reset strided zeros
/*0x1a88*/ PCSharedTaskData             SharedTaskData;  // [HIGH-VALIDATED] state-reset zero block
/*0x1b20*/ TaskTimerData*               pTaskTimerData;  // [HIGH-VALIDATED] state-reset frees list + ptr@+0x1b20=0
/*0x1b28*/ PCQuestHistoryData           QuestHistoryData;  // [HIGH-VALIDATED] ctor FUN_14068cf70(+0x1b28)
/*0x1e48*/ PCStatistics                 PcStatistics;  // [HIGH-VALIDATED] ctor FUN_1406dd560(+0x1e48); reset FUN_1406dd7a0
/*0x1fb0*/ GroupMemberStats             GroupStats;  // [HIGH-VALIDATED] ctor FUN_1406dd500(+0x1fb0); reset FUN_1406dd6c0
/*0x21a8*/ bool                         bIsLfg;  // [HIGH-VALIDATED] state-reset byte@+0x21a8=0
/*0x21ac*/ int                          RaidId;  // [HIGH-VALIDATED] state-reset u64@+0x21ac=0
/*0x21b0*/ int                          GroupID;  // [HIGH-VALIDATED] part
/*0x21b4*/ int                          DaysEntitled;  // [HIGH-VALIDATED] state-reset u32@+0x21b4=0
/*0x21b8*/ bool                         bAutoConsentGroup;  // [HIGH-VALIDATED] state-reset u32@+0x21b8=0x1010101
/*0x21b9*/ bool                         bAutoConsentRaid;  // [HIGH-VALIDATED] packed
/*0x21ba*/ bool                         bAutoConsentGuild;  // [HIGH-VALIDATED] packed
/*0x21bb*/ bool                         bAutoConsentFellowship;  // [HIGH-VALIDATED] packed
/*0x21bc*/ bool                         bPrivateForEqPlayers;  // [HIGH-VALIDATED] state-reset byte@+0x21bc=0
/*0x21c0*/ long                         AchievementFilesModificationTime;  // [HIGH-VALIDATED] state-reset u32@+0x21c0=0
/*0x21c4*/ char                         StationID[0x24];  // [HIGH-VALIDATED] state-reset 4x u64 zeros 0x21c4..0x21e4
/*0x21e8*/ EqGuid                       Guid;  // [HIGH-VALIDATED] ctor+reset u64@+0x21e8=0
/*0x21f0*/ bool                         bBetaBuffed;  // [STILL-SEARCHING] no direct write
/*0x21f4*/ int                          Unknown0x1ee4;  // [HIGH-VALIDATED] state-reset u32@+0x21f4=0
/*0x21f8*/ bool                         bShowHelm;  // [OFFSET-MOVED] state-reset byte@+0x21f8=1 — header swapped w/ MainLevel. ASM disasm search for [*+0x21f8] shows 5 BYTE accesses (mov...
/*0x21f8*/ int                          MainLevel;  // [GHOST] W26 upstream-ghost: upstream's stale offset 0x21f8 for MainLevel. Authoritative placement is 0x21fc (OFFSET-MOVED). A...
/*0x21fc*/ int                          MainLevel;  // [OFFSET-MOVED] header claim 0x21f8; live order reversed. No direct access at 0x21fc found in disasm — MainLevel likely shadow-tracks...
/*0x21fc*/ bool                         bShowHelm;  // [GHOST] W26 upstream-ghost: upstream's stale offset 0x21fc for bShowHelm. Authoritative placement is 0x21f8 (OFFSET-MOVED, 5 ...
/*0x2200*/ int64_t                      LastTestCopyTime;  // [HIGH-VALIDATED] state-reset u64@+0x2200=0
/*0x2208*/ CPlayerPointManager          PointManager;  // [HIGH-VALIDATED] ctor zeros 0x2208..0x2218, vftable 0x140adf7c8 at +0x2220
/*0x2228*/ PointSystemBase              PointSystem;  // [HIGH-VALIDATED] ctor vftable 0x140dcdb10 at +0x2228; helper@+0x2238
/*0x2258*/ uint32_t                     LoyaltyVelocity;  // [HIGH-VALIDATED] state-reset u64@+0x2258=0
/*0x225c*/ uint32_t                     LoyaltyTokens;  // [HIGH-VALIDATED] part
/*0x2260*/ bool                         bHasLoyaltyInfo;  // [STILL-SEARCHING] not isolated in captured writes
/*0x2268*/ ArrayClass<int>              OwnedRealEstates;  // [HIGH-VALIDATED] ctor full ArrayClass init (size/ptr/cap/flag)
/*0x2280*/ ArrayClass<int>              OwnedItemRealEstates;  // [HIGH-VALIDATED] ctor same pattern
/*0x2298*/ ArrayClass<int>              ArchivedRealEstates;  // [HIGH-VALIDATED] ctor same pattern
/*0x22b0*/ char                         OverridePetName[0x40];  // [HIGH-VALIDATED] state-reset byte@+0x22b0=0
/*0x22f0*/ bool                         bCanRequestPetNameChange;  // [HIGH-VALIDATED] state-reset u16@+0x22f0=0
/*0x22f1*/ char                         OverrideFamiliarName[0x40];  // [HIGH-VALIDATED] packed in +0x22f0 u16 write
/*0x2331*/ bool                         bCanRequestFamiliarNameChange;  // [HIGH-VALIDATED] state-reset byte@+0x2331=0
/*0x2338*/ CXStr[11]                    OverrideMercName[11];  // [HIGH-VALIDATED] ctor _eh_vector_constructor(+0x2338,8,11,CXStr)
/*0x2390*/ bool                         bCanRequestMercNameChange;  // [HIGH-VALIDATED] state-reset byte@+0x2390=0
/*0x2394*/ uint32_t                     LegacyExperienceBonus;  // [HIGH-VALIDATED] state-reset u32@+0x2394=0
/*0x2398*/ LockedItemData               LockedItemData;  // [HIGH-VALIDATED] ctor ptr/vftable/zeros + CXStr helper
/*0x23d0*/ PendingRewardList            PendingRewards;  // [HIGH-VALIDATED] ctor FUN_1406c0880(+0x23d0,10,0)
/*0x2418*/ uint8_t[0x20]                WaitingRewards;  // [OFFSET-MOVED] ctor: EQList vftable 0x14089bae8 at +0x2418 + begin/end/cap. Storage is an EQList<X> subobject but upstream declares ...
/*0x2438*/ uint32_t                     DowntimeReductionTime;  // [HIGH-VALIDATED] ctor u32@+0x2438=0
/*0x2440*/ uint64_t                     DowntimeTimerStart;  // [HIGH-VALIDATED] ctor u64@+0x2440=0
/*0x2448*/ float                        ActivityValue;  // [HIGH-VALIDATED] state-reset u32@+0x2448=0
/*0x244c*/ uint32_t                     NextItemId;  // [HIGH-VALIDATED] state-reset u32@+0x244c=0
/*0x2450*/ CXStr                        SharedBank;  // [HIGH-VALIDATED] ctor u64@+0x2450=0; reset CXStr free
/*0x2458*/ CXStr                        BankBuffer;  // [HIGH-VALIDATED] same pattern
/*0x2460*/ CXStr                        LimboBuffer;  // [HIGH-VALIDATED] same
/*0x2468*/ CXStr                        MercenaryBuffer;  // [HIGH-VALIDATED] ctor u64@+0x2468=0
/*0x2470*/ CXStr[7]                     KeyRingBuffer[7];  // [HIGH-VALIDATED] ctor _eh_vector_constructor(+0x2470,8,7,CXStr)
/*0x24a8*/ CXStr                        AltStorageBuffer;  // [HIGH-VALIDATED] ctor u64@+0x24a8=0
/*0x24b0*/ CXStr                        OverflowBuffer;  // [HIGH-VALIDATED] ctor u64@+0x24b0=0
/*0x24b8*/ CXStr                        DragonHoardBuffer;  // [HIGH-VALIDATED] ctor u64@+0x24b8=0
/*0x24c0*/ SoeUtil::String              EquipmentSetsBuffer;  // [HIGH-VALIDATED] ctor vftable 0x140adf7c8 at +0x24c0
/*0x24d8*/ CXStr                        TradeskillDepotBuffer;  // [HIGH-VALIDATED] ctor u64@+0x24d8=0
/*0x24e0*/ bool                         DragonHoardPopulated;  // [HIGH-VALIDATED] state-reset byte@+0x24e0=0
/*0x24e4*/ uint32_t                     DragonHoardCapacity;  // [HIGH-VALIDATED] ctor u64@+0x24e4=0
/*0x24e8*/ uint32_t                     TradeskillDepotCapacity;  // [HIGH-VALIDATED] part
/*0x24ec*/ uint32_t                     TradeskillDepotPopulated;  // [HIGH-VALIDATED] state-reset u32@+0x24ec=0
/*0x24f0*/ uint32_t                     AltStorageTimestamp;  // [HIGH-VALIDATED] inferred adjacency
/*0x24f4*/ ELockoutCharacterReason      LockoutCharacterReason;  // [HIGH-VALIDATED] state-reset u32@+0x24f4=0
/*0x24f8*/ HashTable<ProgressionExperience> ProgressionExp;  // [HIGH-VALIDATED] ctor alloc 0x41-prime hash
/*0x2510*/ CXStr                        ArchivedStorageBuffer;  // [HIGH-VALIDATED] state-reset CXStr free
/*0x2518*/ CXStr                        MailItemsBuffer;  // [HIGH-VALIDATED] state-reset ptr@+0x2518=0
/*0x2520*/ CXStr                        MailItemsDataBuffer;  // [HIGH-VALIDATED] state-reset ptr@+0x2520=0
/*0x2528*/ int                          MailItemsOverCapWarningCount;  // [HIGH-VALIDATED] state-reset u32@+0x2528=0
/*0x252c*/ bool                         UseAdvancedLooting;  // [HIGH-VALIDATED] state-reset u16@+0x252c=0x101
/*0x252d*/ bool                         MasterLootCandidate;  // [HIGH-VALIDATED] packed
/*0x252e*/ bool                         bIsCorrupted;  // [HIGH-VALIDATED] state-reset byte@+0x252e=0
/*0x2530*/ char*                        pCorruptionReport;  // [HIGH-VALIDATED] state-reset frees + ptr@+0x2530=0
/*0x2538*/ char                         InspectText[0x100];  // [HIGH-VALIDATED] state-reset byte@+0x2538=0
/*0x2638*/ HashTable<int>               BlockedSpellsHash;  // [HIGH-VALIDATED] ctor FUN_14008f510(+0x2638,7)
/*0x2650*/ SoeUtil::Array<int>          BlockedSpell;  // [HIGH-VALIDATED] ctor vftable 0x1408be158 at +0x2650
/*0x2668*/ HashTable<int>               BlockedPetSpellsHash;  // [HIGH-VALIDATED] ctor FUN_14008f510(+0x2668,7)
/*0x2680*/ SoeUtil::Array<int>          BlockedPetSpell;  // [HIGH-VALIDATED] ctor vftable 0x1408be158 at +0x2680
/*0x2698*/ ClaimDataCollection          ConsumableFeatures;  // [HIGH-VALIDATED] ctor SoeUtil::Array pattern
/*0x26b0*/ bool                         bGrantItemsRegistered;  // [HIGH-VALIDATED] state-reset byte@+0x26b0=1
/*0x26b8*/ uint64_t                     CreatedGuildID;  // [HIGH-VALIDATED] state-reset u64@+0x26b8=0
/*0x26c0*/ eqtime_t                     GuildCreateTime;  // [HIGH-VALIDATED] state-reset u64@+0x26c0=0
/*0x26c8*/ CXStr                        GuildCreateCharacter;  // [HIGH-VALIDATED] state-reset ptr@+0x26c8=0
/*0x26d0*/ bool                         bInventoryUnserialized;  // [HIGH-VALIDATED] state-reset u32@+0x26d0=0 (4 bools packed)
/*0x26d1*/ bool                         bAltStorageUnserialized;  // [HIGH-VALIDATED] packed
/*0x26d2*/ bool                         bArchivedStorageUnserialized;  // [HIGH-VALIDATED] packed
/*0x26d3*/ bool                         bMailUnserialized;  // [HIGH-VALIDATED] packed
/*0x26d4*/ bool                         bPendingInventorySerialization;  // [HIGH-VALIDATED] packed
/*0x26d8*/ CXStr                        BuyLines;  // [HIGH-VALIDATED] state-reset FUN_1405a4a80(+0x26d8, default)
/*0x26e0*/ ArrayClass<CXStr>            OfflineTraderSoldItems;  // [HIGH-VALIDATED] ctor u32/ptr/u32/byte pattern
/*0x26f8*/ ArrayClass<CXStr>            OfflineBuyerBoughtItems;  // [HIGH-VALIDATED] same pattern
/*0x2710*/ uint32_t                     Krono;  // [HIGH-VALIDATED] state-reset u64@0x2710=0
/*0x2714*/ uint32_t                     CursorKrono;  // [HIGH-VALIDATED] part
/*0x2718*/ int64_t                      MercAAExp;  // [HIGH-VALIDATED] state-reset u64@+0x2718=0
/*0x2720*/ int                          MercAAPoints;  // [HIGH-VALIDATED] state-reset u64@+0x2720=0
/*0x2724*/ int                          MercAAPointsSpent;  // [HIGH-VALIDATED] part
/*0x2728*/ ArrayClass<MercenaryAbilityInfo*> MercenaryAbilities;  // [HIGH-VALIDATED] ctor alloc 0xc8 + cap=25
/*0x2740*/ UnknownCharacterStruct1*     Unknown26c8;  // [HIGH-VALIDATED] state-reset: deref + realloc 0x28-byte struct
/*0x2748*/ AchievementTable             CompletedAchievements;  // [HIGH-VALIDATED] ctor alloc 0x33-prime hash
/*0x2760*/ AchievementSubComponentCountTable CompletedEventBasedSubComponents;  // [HIGH-VALIDATED] ctor FUN_14008f510(+0x2760, param_2)
/*0x2778*/ AchievementSubComponentCountTable OpenEventBasedSubComponents;  // [HIGH-VALIDATED] ctor FUN_14008f510(+0x2778, param_3)
/*0x2790*/ int                          LastFellowshipJoin;  // [HIGH-VALIDATED] state-reset u64@+0x2790=0
/*0x2798*/ int64_t                      Vitality;  // [HIGH-VALIDATED] state-reset u64@+0x2798=0
/*0x27a0*/ int64_t                      AAVitality;  // [HIGH-VALIDATED] state-reset u64@+0x27a0=0
/*0x27a8*/ int[35]                      FreeToPlayUnlocks;  // [HIGH-VALIDATED] state-reset u64 sweep 0x27a8..0x2830
/*0x2e50*/ void*                        (CZC_secondary_vftable);  // [HIGH-VALIDATED] ALIAS: PzC ctor 1402ee1e0 installs 0x140955a38 (CZC 2nd vftable, full qword); not a C++ data member. The vbase-adjust...
/*0x2e58*/ uint32_t[3]                  Flags[0];  // [HIGH-VALIDATED] PzC ctor 1402ee242 qword-clear 0x2e58..0x2e5f; dtor 1402e9061 matches. Type widened to uint32_t[3] to match upstream ...
/*0x2e5c*/ uint32_t                     Flags[1];  // [HIGH-VALIDATED] PzC ctor 1402ee242 qword-clear (upper 4B of 0x2e58 qword)
/*0x2e60*/ uint32_t                     Flags[2];  // [HIGH-VALIDATED] PzC ctor 1402ee249 standalone dword-clear; dtor 1402e9068 matches
/*0x2e64*/ uint32_t                     TransfersReceived;  // [HIGH-VALIDATED] PzC ctor 1402ee22d qword-clear; PcClient ctor 1402e3972 overrides to 1
/*0x2e68*/ int32_t                      LastLanguageSpoken;  // [HIGH-VALIDATED] PzC ctor covered by qword clear at 1402ee22d (upper 4B)
/*0x2e6c*/ int32_t                      CurPowerSourceDrain;  // [HIGH-VALIDATED] PzC ctor 1402ee234; readers via pLocalPC at 14042edd4 + 140436e4e (int-to-CXStr formatter)
/*0x2e70*/ SoeUtil::List_vftable*       AlchemyBaseSkillBonusList_vptr;  // [HIGH-VALIDATED] PzC ctor 1402ee214-21b: SoeUtil::List<AlchemyBonusSkillData*> vftable 0x14089bae8. Upstream d78e8ac PcClient.h:1119 /...
/*0x2e78*/ ListNode*                    AlchemyBaseSkillBonusList.pHead;  // [HIGH-VALIDATED] PzC ctor 1402ee225 zero; readers 1402f296a list-destructor walk + 1402f3607/1402f9319
/*0x2e80*/ ListNode*                    AlchemyBaseSkillBonusList.pTail;  // [HIGH-VALIDATED] PzC ctor 1402ee229 zero; dtor 1402ee2b9
/*0x2e88*/ void*                        AlchemyBaseSkillBonusList.extra;  // [HIGH-VALIDATED] PzC ctor 1402ee221 zero; dtor 1402ee2b5
/*0x2e90*/ uint32_t                     MomentumBalance;  // [HIGH-VALIDATED] PzC ctor 1402ee23b qword-clear; setter thunk 14020b0d0; readers 140415aa9 pLocalPC+imul*100, 14051c067 xmm gauge
/*0x2e94*/ uint32_t                     LoyaltyRewardBalance;  // [HIGH-VALIDATED] PzC ctor 1402ee23b qword-clear (upper 4B); setter thunk 14020b0e0; getter 1402cc823; UI readers 1401ed850/14041582a/1...
/*0x2e98*/ ExtendedTargetList*          pExtendedTargetList;  // [HIGH-VALIDATED] PcClient ctor 1402e3417 null-init; 1402e3a4b sets to new ExtendedTargetList (0x30 bytes)
/*0x2ea0*/ int64_t                      DowntimeStart;  // [HIGH-VALIDATED] PcClient ctor 1402e3983 zero
/*0x2ea8*/ int32_t                      Downtime;  // [HIGH-VALIDATED] PcClient ctor 1402e397c zero
/*0x2eac*/ bool                         InCombat;  // [HIGH-VALIDATED] PcClient ctor 1402e3433 byte=0
/*0x2ead*/ bool                         bOverrideAvatarProximity;  // [HIGH-VALIDATED] PcClient ctor 1402e398a byte=0
/*0x2eb0*/ CGroup*                      Group;  // [HIGH-VALIDATED] PcClient ctor 1402e3991 null
/*0x2eb8*/ bool                         bIAmCreatingGroup;  // [HIGH-VALIDATED] PcClient ctor 1402e343a byte=0
/*0x2ec0*/ Item**                       ItemsPendingID.pItems;  // [HIGH-VALIDATED] PcClient ctor 1402e341e null
/*0x2ec8*/ uint64_t                     ItemsPendingID.Count;  // [HIGH-VALIDATED] PcClient ctor 1402e3425 zero
/*0x2ed0*/ uint64_t                     ItemsPendingID.Capacity;  // [HIGH-VALIDATED] PcClient ctor 1402e342c zero; later 1402e3a98 grows to 2
/*0x2ed8*/ eParcelStatus                ParcelStatus;  // [HIGH-VALIDATED] PcClient ctor 1402e34b8 zero
/*0x2edc*/ int                          SubscriptionDays;  // [HIGH-VALIDATED] PcClient ctor 1402e3aa3 dword=-1
/*0x2ee0*/ short[7]                     BaseKeyRingSlots;  // [HIGH-VALIDATED] PcClient ctor 1402e34d0 tight-loop 7 shorts zero
/*0x2eee*/ bool                         bPickZoneFewest;  // [HIGH-VALIDATED] POD trailing bool; default-constructed false
/*0x2ef0*/ int                          Unknown0x28a4;  // [HIGH-VALIDATED] PcClient ctor 1402e34bf zero (name matches upstream)
/*0x2ef4*/ int32_t                      (vbase_displacement);  // [HIGH-VALIDATED] ALIAS: MSVC vbase disp written by PcClient ctor 1402e3413 ([rdi+0x2ef4]=-8)
/*0x2ef8*/ void*                        (CharacterBase_vftable);  // [HIGH-VALIDATED] ALIAS: PcClient ctor 1402e3400 installs CB vftable 0x140955a40; compiler-generated
/*0x3298*/
};

// SIZE_CHECK(PcClient, 0x3298);  // uncomment once integrated

} // namespace eqlib

